<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="5" assertions="4" errors="2" warnings="0" failures="0" skipped="0" time="0.276367">
    <testsuite name="App" tests="5" assertions="4" errors="2" warnings="0" failures="0" skipped="0" time="0.276367">
      <testsuite name="ExampleDatabaseTest" file="C:\xampp\htdocs\tests\database\ExampleDatabaseTest.php" tests="2" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="0.244812">
        <testcase name="testModelFindAll" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="C:\xampp\htdocs\tests\database\ExampleDatabaseTest.php" line="17" assertions="0" time="0.243064">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testModelFindAll
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class "SQLite3" not found

C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\BaseConnection.php:418
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:48
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:74
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:54
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
        <testcase name="testSoftDeleteLeavesRow" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="C:\xampp\htdocs\tests\database\ExampleDatabaseTest.php" line="28" assertions="0" time="0.001748">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testSoftDeleteLeavesRow
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class "SQLite3" not found

C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\BaseConnection.php:418
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:48
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:74
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php:54
C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php:248</error>
        </testcase>
      </testsuite>
      <testsuite name="ExampleSessionTest" file="C:\xampp\htdocs\tests\session\ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.001496">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="C:\xampp\htdocs\tests\session\ExampleSessionTest.php" line="11" assertions="1" time="0.001496"/>
      </testsuite>
      <testsuite name="HealthTest" file="C:\xampp\htdocs\tests\unit\HealthTest.php" tests="2" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.030060">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="C:\xampp\htdocs\tests\unit\HealthTest.php" line="13" assertions="1" time="0.001020"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="C:\xampp\htdocs\tests\unit\HealthTest.php" line="18" assertions="2" time="0.029040"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
